### ISSUE TITLE
An error occured while processing your request, Reference #30

### ISSUE THREAD

**Issue by candyking123** [mistertest/xcloud-shield#15]
Since yesterday when I try to start Xcloud Shield on Shield TV Pro (2019) I get stuck in the white screen with the following message: "An error occured while processing your request. Reference #30.xxxxxxx.xxxxxxxxxx.xxxxxxx". The beginning of the reference number is always 30, the numbers after it keep changing.

I tested Xcloud on my PC too and it seems to work normally, so there should be nothing wrong with my account.

I played GTA San Andreas yesterday and I exited the game using the back button of the controller. The app asked something about if I want to close the game or something to which I chose yes. After that this white screen with the reference number came for the first time and hasn't gone away since.

I deleted Xcloud Shield version 4.3 and installed 4.4 but the problem stayed the same.

I am located in Finland.

Thanks a lot for making the app!

**Comment by candyking123** [comment]
Nevermind.. There's something wrong with https://www.xbox.com at the moment. Can't access it on any device I have. I get the same error message with PC and on my phone too when trying to get to that homepage. PC app is working.

**Comment by mistertest** [comment]
@candyking123  Hello. Yes it was more about a global issue from somes updates from Microsoft xbox

**Comment by mistertest** [comment]
@candyking123 So now Xcloud shield is working ? I can't test it on my living room for now.
