### ISSUE TITLE
Xbox One Controller no inputs

### ISSUE THREAD

**Issue by JReming85** [mistertest/xcloud-shield#27]
Do I have to install anything else to get the xbox controller to work with this or change some setting?

It navigates fine but when I load up a game (Katamari Damacy REROLL) I cant get past the intro Press A to start, Press X to change profile

Controller works fine for Gamestream, Steam, and Luna

Also tried it with another game, The Gunk and same issue.  Its like controller just doesnt have access to the game window

**Comment by mistertest** [comment]
Hi. Go see all issues resolved about controllers and read the page project section about controllers. But globaly 2 controllers connected are not authorized and there are somes conflicts with unofficials remote and keyboard usb/bluetooth.

**Comment by JReming85** [comment]
Understood, most likely because I have a mouse plugged in as well.

Thanks for the quick response and solution as well as making the whole project.

**Comment by ExSport** [comment]
If it will not work, try to sideload official app and test it there. It should work and unlock functionality also in this unofficial app. It worked for me like that.
https://github.com/mistertest/xcloud-shield/issues/11#issuecomment-1031917769
Btw. @mistertest still waiting for beta with 720p and non-english language support so I can donate😎
Thank you
