### ISSUE TITLE
App freezes upon game list (main page)

### ISSUE THREAD

**Issue by gamemodderz** [mistertest/xcloud-shield#34]
Prob will never work on my android tv as its an EKO cheap off brand running android 9, have xbox one controller hooked up but freezes when i open the app, nvidia app works fine on the same tv. any info i can provide to help lmk

**Comment by mistertest** [comment]
Hi, The App is based on Webview like the Brower "Open Browser", so if you have trouble with Open browser app you'll have the sames issues with Xcloud Shield. Perhaps you can test to update the Webview on your android tv with your google play.
Search "Webview" in google play and update it if needed. But yes the app, is thinked for the powerfull of the shield tv and the paramereters of Graphic rendering are settings on maxium. Perhaps with a setting on normal rendering , it will be runing normaly on your tv. But this parameters are not accessible for users, it's in app. You'll can try to test soon, a version with this normal rendering graphic.

**Comment by gamemodderz** [comment]
Fixed 🤙, currently getting “we’ll be right back” screen during loading fortnite.
